### ISSUE TITLE
3D Graphic displaced from axes.

### ISSUE THREAD

**Issue by doccpu75** [PDLPorters/pdl#337] opened 2021-09-06 23:31 UTC
I installed TriD into a 64 bit Bionic Ubuntu and found that the perldl demo worked except that the data plots were displaced from the axes so far that on the inital display they weren't visible. Torquing around the graph revealed the data graphs well off of the axes.This is only true on the 64 bit version. Installed on a 32 bit Linux gives the proper results.

**Comment by mohawk2** [comment] 2021-09-07 20:48
I've just run the `demo 3d` (is that the one you're trying), and the first 3D thing is axes that fill about half the window, which looks right. Can you tell me a little more about what you're seeing, so I can reproduce this?

**Comment by mohawk2** [comment] 2021-12-26 06:02
Please provide more information if you would like us to look into this :-)

**Comment by mohawk2** [comment] 2022-03-01 04:08
In addition to this, `nokeeptwiddling3d` currently seems to be irreversible, and `demo 3dgal` causes `perldl` history to get lost, together with an error from line 234 of POGL/OpenGL.pm (a call to `glutDisplayFunc()`).

**Comment by mohawk2** [comment] 2022-03-10 23:13
The history getting lost was happening with Term::ReadLine::Gnu 1.37. After upgrading to 1.42, it ceases to happen.

`nokeeptwiddling3d` now behaves correctly in current `master`, and the above-linked commit solves the error.

**Comment by mohawk2** [comment] 2022-03-11 03:00
I believe that lost-history problem will be similar to this: https://developer.blender.org/T43491

OpenGL loads LLVM (that's how it compiles its scripty stuff) which loads `libedit.so`. This, not very surprisingly, has similarly-named symbols to GNU readline (since they do similar things). The GNU readline stuff in Term::ReadLine::Gnu, when called, gets dynamically-loaded symbols with the right names for its purposes, from the wrong place (libedit) which therefore have the wrong values. This is easily worked-around by calling the GNU readline history-reading function early during startup.

**Comment by mohawk2** [comment] 2022-03-13 07:49
It's reasonably certain that this problem is caused by the aggregate functions changing to returning ndarrays, not Perl scalars.

**Comment by mohawk2** [comment] 2022-03-13 09:19
I would expect the version on the 32-bit Linux referred to by the OP was the packaged version of PDL, which tends to be older than the released one, rather than the latest. The bug was caused by the change in aggregate functions in 2.056, and not catching the use of those in the TriD code.

The `keeptwiddling3d` problem referred to above was my confusion - once you turn that setting back on, you still have to do `twiddle3d` in order to wait for user input, due to the lack of an event loop in Perl.

The above-linked commit, at long last, resolves this problem, so I am closing this.

**Closed by mohawk2** 2022-03-13 09:19 UTC
Labels: demos
