### ISSUE TITLE
Fails to build on various architectures

### ISSUE THREAD

**Issue by sebastic** [PDLPorters/pdl#369] opened 2022-01-11 13:56 UTC
The Debian package for PDL 2.066 fails to build on various architectures, see:

 https://buildd.debian.org/status/package.php?p=pdl&suite=experimental

 * [arm64](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=arm64&ver=1%3A2.066-1%7Eexp1&stamp=1641893095&raw=0)
   ```
   Test Summary Report
   -------------------
   t/bad.t              (Wstat: 256 Tests: 119 Failed: 1)
     Failed test:  118
     Non-zero exit status: 1
   t/ops-bitwise.t      (Wstat: 0 Tests: 82 Failed: 0)
     TODO passed:   68-71
   t/ops.t              (Wstat: 0 Tests: 82 Failed: 0)
     TODO passed:   68-71
   t/pdl_from_string.t  (Wstat: 0 Tests: 144 Failed: 0)
     TODO passed:   60-62
   t/primitive.t        (Wstat: 0 Tests: 100 Failed: 0)
     TODO passed:   11-12
   Files=35, Tests=1590, 42 wallclock secs ( 0.37 usr  0.19 sys + 39.83 cusr  3.98 csys = 44.37 CPU)
   Result: FAIL
   Failed 1/35 test programs. 1/1590 subtests failed.
   ```
 * [armel](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=armel&ver=1%3A2.066-1%7Eexp1&stamp=1641893493&raw=0)
    ```
   Test Summary Report
   -------------------
   t/linfit.t               (Wstat: 11 Tests: 0 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   t/lm.t                   (Wstat: 11 Tests: 0 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   t/slatec-polyfit-weight.t (Wstat: 65280 Tests: 2 Failed: 2)
     Failed tests:  1-2
     Non-zero exit status: 255
     Parse errors: No plan found in TAP output
   t/slatec.t               (Wstat: 11 Tests: 3 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   Files=4, Tests=5,  1 wallclock secs ( 0.09 usr  0.03 sys +  1.09 cusr  0.18 csys =  1.39 CPU)
   Result: FAIL
   Failed 4/4 test programs. 2/5 subtests failed.
   ```
 * [armhf](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=armhf&ver=1%3A2.066-1%7Eexp1&stamp=1641893314&raw=0)
   ```
   Test Summary Report
   -------------------
   t/linfit.t               (Wstat: 11 Tests: 0 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   t/lm.t                   (Wstat: 11 Tests: 0 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   t/slatec-polyfit-weight.t (Wstat: 65280 Tests: 2 Failed: 2)
     Failed tests:  1-2
     Non-zero exit status: 255
     Parse errors: No plan found in TAP output
   t/slatec.t               (Wstat: 11 Tests: 3 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   Files=4, Tests=5,  1 wallclock secs ( 0.10 usr  0.04 sys +  0.88 cusr  0.15 csys =  1.17 CPU)
   Result: FAIL
   Failed 4/4 test programs. 2/5 subtests failed.
   ```
 * [i386](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=i386&ver=1%3A2.066-1%7Eexp1&stamp=1641892885&raw=0)
   ```
   Test Summary Report
   -------------------
   t/linfit.t               (Wstat: 11 Tests: 0 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   t/lm.t                   (Wstat: 11 Tests: 0 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   t/slatec-polyfit-weight.t (Wstat: 65280 Tests: 2 Failed: 2)
     Failed tests:  1-2
     Non-zero exit status: 255
     Parse errors: No plan found in TAP output
   t/slatec.t               (Wstat: 11 Tests: 3 Failed: 0)
     Non-zero wait status: 11
     Parse errors: No plan found in TAP output
   Files=4, Tests=5,  1 wallclock secs ( 0.02 usr  0.02 sys +  0.56 cusr  0.06 csys =  0.66 CPU)
   Result: FAIL
   Failed 4/4 test programs. 2/5 subtests failed.
   ```
 * [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=ppc64el&ver=1%3A2.066-1%7Eexp1&stamp=1641893087&raw=0)
   ```
   Test Summary Report
   -------------------
   t/autoload.t         (Wstat: 256 Tests: 3 Failed: 1)
     Failed test:  2
     Non-zero exit status: 1
   t/bad.t              (Wstat: 256 Tests: 119 Failed: 1)
     Failed test:  118
     Non-zero exit status: 1
   t/ops-bitwise.t      (Wstat: 0 Tests: 82 Failed: 0)
     TODO passed:   68-71
   t/ops.t              (Wstat: 0 Tests: 82 Failed: 0)
     TODO passed:   68-71
   t/pdl_from_string.t  (Wstat: 0 Tests: 144 Failed: 0)
     TODO passed:   60-62
   t/primitive.t        (Wstat: 0 Tests: 100 Failed: 0)
     TODO passed:   11-12
   Files=35, Tests=1590, 39 wallclock secs ( 0.35 usr  0.07 sys + 36.80 cusr  2.89 csys = 40.11 CPU)
   Result: FAIL
   Failed 2/35 test programs. 2/1590 subtests failed.
   ```
 * [s390x](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=s390x&ver=1%3A2.066-1%7Eexp1&stamp=1641892995&raw=0)
   ```
   Test Summary Report
   -------------------
   t/fits.t (Wstat: 65280 Tests: 118 Failed: 0)
     TODO passed:   12, 16, 25, 29, 38, 44, 50, 59
     Non-zero exit status: 255
     Parse errors: No plan found in TAP output
   Files=1, Tests=118,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.10 cusr  0.00 csys =  0.11 CPU)
   Result: FAIL
   Failed 1/1 test programs. 0/118 subtests failed.
   ```

**Comment by mohawk2** [comment] 2022-01-11 16:20
Thank you! We'll take a look.

**Comment by mohawk2** [comment] 2022-01-11 17:18
Is there any way I could get a login to machines with these architectures, so I could run `gdb` or similar to get a stack trace? The i386, armel, armhf Slatec failures look like they might be SEGVs, for a start.

**Comment by sebastic** [comment] 2022-01-11 17:32
Not easily, you'd need a sponsor for a guest account on the Debian porterboxes:

 https://dsa.debian.org/doc/guest-account/

i386 you can easily test in a chroot or VM on an amd64 system.

arm64 and a few other architectures also have reasonably good emulation in QEMU, e.g;

 https://wiki.debian.org/Arm64Qemu

Amazon may also still have the free tier for their arm64 VMs.

**Comment by mohawk2** [comment] 2022-01-11 17:36
Thanks, that's a good start!

A common theme, including on ppc64, is:
```
Badvalue is set to 0 or 1. This will cause data loss when using badvalues for comparison operators. at ops.pd line 137.
	PDL::Ops::__ANON__(PDL=SCALAR(0x1002b456840), 0, "") called at t/bool.t line 23
```

Despite the large number of failures and diverse architectures, my feeling (or at least hope) is this is a small number of errors.

**Comment by mohawk2** [comment] 2022-01-11 17:40
Also, you wouldn't happen to have any insight into how to get any of these environments (at all) going with GitHub actions? I'd really like to catch this stuff in our CI. I'd also like to routinely run `lintian` to catch those errors sooner too.

By the way, is there any value in PDL's current `debian` directory existing? I've excluded it now from our `MANIFEST` since I saw one of your patches does that, but I want it to be relevant / helpful, or I'll remove it entirely (or replace it if you'd like to have that as the canonical location for Debian stuff, which means we could CI it with every commit - do other projects do that?).

**Comment by mohawk2** [comment] 2022-01-11 17:43
On that topic, I saw ironically that you recently dropped `proj-bin` as a dep. With the new Proj v6+ support, it would be effective to add them back, have Alien::proj as a purely build-only dep, and get the Proj4 modules in Debian PDL again?

**Comment by sebastic** [comment] 2022-01-11 18:16
> Despite the large number of failures and diverse architectures, my feeling (or at least hope) is this is a small number of errors.

Agreed. If you start by fixing the issues on i386 you likely have fixed those issues on the other 32bit architectures too.

> Also, you wouldn't happen to have any insight into how to get any of these environments (at all) going with GitHub actions? I'd really like to catch this stuff in our CI.

I have no experience with GitHub actions, a little searching the docs finds me this which might be a good start:

 https://github.com/marketplace/actions/run-on-architecture

> I'd also like to routinely run lintian to catch those errors sooner too.

lintian only makes sense for Debian package builds, you could implement some of its tests in CI though.

> By the way, is there any value in PDL's current debian directory existing? I've excluded it now from our MANIFEST since I saw one of your patches does that, but I want it to be relevant / helpful, or I'll remove it entirely (or replace it if you'd like to have that as the canonical location for Debian stuff, which means we could CI it with every commit - do other projects do that?).

If you want to build Debian packages yourself from the PDL source tree, there is still value keeping the directory.

It is not used for the package in Debian, we maintain our own packaging.

Since we have control over the infrastructure like Salsa, I will always maintain packaging there. I'm not an upstream developer, or even a user, which makes maintaining the packaging in the upstream repo make little sense.

If you get more involved with packaging PDL and its dependencies in Debian, you are in a much better position to maintain the upstream packaging.

> On that topic, I saw ironically that you recently dropped proj-bin as a dep. With the new Proj v6+ support, it would be effective to add them back, have Alien::proj as a purely build-only dep, and get the Proj4 modules in Debian PDL again?

Alien::proj is not packaged for Debian, and since I don't actually use PDL and only keep the packaging on life support, I'm not willing to package it. This is why we had the pkg-config discussion to get the build flags in the other issue, it would remove the need for a new dependency to get packaged.

If I can build PDL with PROJ support by just reverting the removal the libproj-dev & proj-bin (build) dependencies I will do so. Based on the discussion I expected the pkg-config support to be available in PDL 2.064 and planned to revert the removal, but because it still requires Alien::proj I left it as-is.

**Comment by sebastic** [comment] 2022-01-14 08:58
Regarding Slatec, be aware of these changes:

 https://salsa.debian.org/perl-team/modules/packages/pdl/-/blob/master/debian/patches/slatec_default_integer_8.patch

**Comment by mohawk2** [comment] 2022-01-14 09:15
Thanks!

**Comment by sebastic** [comment] 2022-01-14 16:44
> I believe that will pass at least on arm64, and possibly others.

Only arm64 so far:

 https://buildd.debian.org/status/package.php?p=pdl&suite=experimental

**Comment by mohawk2** [comment] 2022-01-15 03:58
I've updated Slatec and Minuit to be (hopefully) 64-bit aware, and will release that in due course.

Meanwhile, the FITS failures all show:
```
substr outside of string at /<<PKGBUILDDIR>>/IO/FITS/../../blib/lib/PDL/IO/FITS.pm line 895.
```
which is code that uses the `get_dataref` mechanism to read directly into ndarray's data using `substr`. This implies the sizes of ndarrays might be wrong, which might be due to them being of an unexpectedly small type.

**Comment by mohawk2** [comment] 2022-01-17 15:31
This was in fact a small number of problems:
- recently-added tests for the long-existing `rfits` with compression exposed an equally-long-existing bug on big-endian systems: unconditional byte-swapping rather than checking for endian-ness
- the new `SByte` type was a `char` which on some systems is still unsigned, which with our policy of default badvalues on supposedly signed types being the MIN value led to the badvalue on `SByte` being 0, which caused test failures due to warning in that situation
- the comparison in `t/autoload.t` was inappropriately precise, doing an exact-equality test on floating-point numbers
- the Fortran libraries (Minuit and Slatec) were not 64-bit safe, and making them so was not helped by Fortran's semantics lacking C's header-files concept, so it instead just assumes that the types (and particularly sizes) of arguments being passed are correct (Minuit was easy because being one huge file, the compiler could spot inconsistency between parameters and arguments)

I'm leaving this issue open because we haven't yet formally confirmed that this actually is all the problems yet, but any remaining ones will hopefully be small and easily solved.

Lessons learned along the way:
- `qemu` is a great tool for locally trying various architectures, though it's very slow, and actual CI is obviously a good idea; we might usefully set up jobs that only get run for tags, like Cygwin currently
- the Debian packagers have got space-age version-management technology, including tracking a `pdlapi` (for the ABI), which will be very beneficial to mimic/learn from in packaging for Homebrew, and conceivably Chocolatey

**Comment by mohawk2** [comment] 2022-01-17 15:52
Packaging notes for myself:
- Alien::proj needs patching-over to a `pkg-config` call for now
- the OpenGL::GLUT needs patching-over to use just normal OpenGL, with the caveat that handling closed windows will be broken again
- both of those might be solved more sustainably by packaging both distros properly
- the suggested libpdl-fftw-perl needs updating to FFTW3 or more likely removing
- same for `libpdl-graphics-plplot-perl` and `libmodule-compile-perl`
- the `libx*` and `x11proto-core-dev` build deps want a review
- the `r-pdl` conflicts stuff may be obsolete
- should we also recommend ffmpeg?

PDL::FAQ will want a review of its packaging / installation notes. Also, do we actually really need to dep on Term::ReadKey at all?

**Comment by mohawk2** [comment] 2022-01-18 21:24
I did some extra checks for Slatec, using these techniques; first I replaced all the individual files in `Libtmp/Slatec/Makefile` with:
```make
FFLAGS=-fPIC -std=legacy -cpp

slatec/bigun$(OBJ_EXT): slatec/bigun.f
        gfortran -c  $(FFLAGS)  -o slatec/bigun$(OBJ_EXT)   slatec/bigun.f
```

Then iterated to find further problems and fix them using:
```shell
(cd Libtmp/Slatec/;
  (for x in slatec/[c-z]*.f; do echo "#line 1 \"$x\""; cat $x; done) >bigun.f; mv bigun.f slatec/;
  time make test
) |&less
```
which lets the compiler see all the Fortran at once and so detect problems, while with the `-cpp` and `#line` directives still show the right file and line numbers. Interestingly, because there are 112 files there, it takes something like 2s to compile them individually, but only about 1.1s to compile the concatenated file.

**Comment by sebastic** [comment] 2022-01-19 08:14
> I'm leaving this issue open because we haven't yet formally confirmed that this actually is all the problems yet, but any remaining ones will hopefully be small and easily solved.

With the changes in 2.068_02 the build failure is fixed on ppc64el & s390x.

It still fails on [armel](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=armel&ver=1%3A2.068-1%7Eexp2&stamp=1642578926&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=armhf&ver=1%3A2.068-1%7Eexp2&stamp=1642577270&raw=0), and [i386](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=i386&ver=1%3A2.068-1%7Eexp2&stamp=1642576740&raw=0).

**Comment by mohawk2** [comment] 2022-01-20 02:04
The most recent build shows failures for 32-bit (next one should be fine), but also GSL::LINALG failures on at least sparc64, ppc64; specifically the `LU_det` returns 0 rather than the expected roughly 0.07+1e-9i. No idea why.

**Comment by mohawk2** [comment] 2022-01-20 21:40
The latest problem is that `t/transform.t` fails on 32-bit, on only one test. So far this is down to the way `whichND` uses `index` for slices to update columns of the resulting coordinates affecting more than just the indicated column, but only on 32-bit!

**Comment by sebastic** [comment] 2022-02-07 21:16
While the package now builds successfully on all release architectures, it only does so because PDL::GSL::LINALG is disabled on mips64el/mipsel, powerpc/ppc64, and sparc64.

To truly resolve this issue that should be fixed too.

**Comment by mohawk2** [comment] 2022-03-29 19:21
That module is disabled on those platforms due to a probable compiler bug which (as you know) has been reported. Nothing at all can be done in this library to fix that. @sebastic Do you agree, and if so could you close this? As you can see in the linked comment above, this thing staying open is causing people to get an inaccurate picture of this library's stability.

**Comment by sebastic** [comment] 2022-03-29 19:29
Nothing has changed since my last comment, so I don't think this issue can be closed.

If you're unable or unwilling to truly resolve the issue on those architectures, please state so explicitly to inform any possible users of those architectures that they can't expect a fully functional PDL like on more popular architectures.

It's quite possible that there are zero actual users of PDL on those architectures, so it's quite acceptable to not spend more time on them.

**Comment by mohawk2** [comment] 2022-03-29 19:34
When you say "explicitly stated", where do you have in mind? It certainly seems valid to move the patch from the Debian packaging into main PDL, since it's in no way specific to Debian.

**Comment by sebastic** [comment] 2022-03-29 19:44
Bare minimum would be to state that in the comment with which this issue is closed.

Upstreaming the changes from the Debian package is an option, although I'm not aware of any distros other than the BSDs also supporting those architectures.

**Comment by mohawk2** [comment] 2022-03-29 19:53
I didn't know about other platforms supporting those, though it's great they do. I feel like upstreaming that patch would ironically be bad by hiding information (and I don't know for sure that clang breaks in this way) - hopefully they'd report an issue.

I'll thank you again for the huge effort you've made in helping us fix the real problems this library had on those various architectures!

**As of this writing, PDL::GSL::LINALG does not work on Debian on mips64el/mipsel, powerpc/ppc64, and sparc64 - it is believed this is due to an actual compiler bug.** Therefore this issue is being closed. Please report any difficulties on here (since I recently learned non-maintainers can't reopen issues) and I'll reopen it, else please open a new one.

**Closed by mohawk2** 2022-03-29 19:53 UTC

**Comment by eli-schwartz** [comment] 2024-03-31 15:56
@sebastic you may want to check out #468 -- it contains other 64bit fixes, this time exposed by LTO passes (which are very good at tickling the optimizer, and also allows the diagnostic analysis to get a full-program view of the compiled library -- very useful for detecting latent bugs that in practice only produce incorrect results on non-amd64 hardware!!)
