### ISSUE TITLE
"Zeroes" allocates for 4 bytes integer type regardless of 1st (type) argument

### ISSUE THREAD

**Issue by vadim-160102** [PDLPorters/pdl#274] opened 2020-01-14 10:35 UTC
It seems "zeroes" (and "ones", etc.) allocates and initiates for something like "int32_t", for "byte" and "short" type argument, and then down-sizes and returns the new piddle.

```
use strict;
use warnings;
use feature 'say';
use Time::HiRes 'time';
use PDL;

# $PDL::BIGPDL = 1;

{
    my $t = time;
    my $p = zeroes byte, 10_000_000;
    say time - $t;
}
{
    my $t = time;
    my $p = PDL-> new_from_specification( byte, 10_000_000 );
    $p-> inplace-> minus( $p, 0 );
    say time - $t;
}

__END__

0.0427219867706299
0.0108280181884766

```
See 4x speed difference; and with piddle size ~269 Mb, the BIGPDL line needs to be un-commented, i.e. allocation gets above 1 Gb.

Perl version   : 5.30.1 / MSWin32-x64-multi-thread
PDL version    : 2.019

But it wasn't so as recent as 
Perl version   : 5.26.0 / MSWin32-x64-multi-thread
PDL version    : 2.018

**Comment by d-lamb** [comment] 2020-03-25 17:00
Thanks for the report.

I can confirm that `zeroes` is much slower than `new_from_specification`.  `zeroes` calls `new_from_specification` internally, and then assigns 0 to each element of the piddle with a line of code: `$pdl.=0;`.  Running a variant of your code using [Devel::NYTProf](https://metacpan.org/pod/Devel::NYTProf) reveals that it is the assignment `.=` that is time intensive.  I tried, e.g., replacing `.=0` with `*=0`.  The resulting code is faster, but causes test failures that are not always reproducible.  I am not yet sure why.  It will require some deep investigation, but it may not be worth the time.

I can also confirm the apparent issue with intermediate storage, as seen in this pdl shell session.
~~~~pre
pdl> $z= zeroes(byte,2.6E8);
pdl> ?$z
This variable is   Byte D [260000000]          P          247.96MB

pdl> $z= zeroes(byte,2.7E8);
	(in cleanup) Probably false alloc of over 1Gb PDL! (set $PDL::BIGPDL = 1 to enable) at /Users/derek/local/lib/perl5/darwin-thread-multi-2level/PDL/Core.pm line 2534.
Probably false alloc of over 1Gb PDL! (set $PDL::BIGPDL = 1 to enable) at /Users/derek/local/lib/perl5/darwin-thread-multi-2level/PDL/Core.pm line 814.
~~~~

I tried this in PDL 2.018 and got the same results both for code speed and intermediate storage, so I can NOT confirm that this is a PDL regression.  If you still find a difference with PDL 2.018 (I note you also have a different Perl version), please attach the output of `perldl -V` from both setups.  There do not seem to be any changes to the part of PDL that handles such low-level functions between 2.018 and 2.019, so if you do see a difference it is possible that it comes from differences in how your Perls were compiled, and that may give us a hint on where to look.

**Comment by vadim-160102** [comment] 2020-03-28 08:19
Hi, thanks for looking into this. Below is output of "perldl -V" for: 

- 5.26/2.018 (good -- same speed for OP script cases, success allocating 2.7E8 bytes);
- 5.30/2.019 (bad -- 4x speed difference for OP script, failure to allocate 2.7E8 bytes). 

Both distributions installed (unzipped) from pre-packed "Strawberry Perl PDL edition". I thought 4x slower speed is direct consequence of having to zero 4x more memory? I.e. fixing allocation will fix speed.

```
perlDL shell v1.357
 PDL comes with ABSOLUTELY NO WARRANTY. For details, see the file
 'COPYING' in the PDL distribution. This is free software and you
 are welcome to redistribute it under certain conditions, see
 the same file for details.

Summary of my PDL configuration

VERSION: PDL v2.018 (supports bad values)

$%PDL::Config = {
                  'PROJ_INC' => undef,
                  'WITH_HDF' => '1',
                  'GSL_INC' => undef,
                  'HIDE_TRYLINK' => '1',
                  'MINUIT_LIB' => undef,
                  'GL_BUILD' => '1',
                  'POSIX_THREADS_LIBS' => undef,
                  'TEMPDIR' => 'C:\\Users\\vadim\\AppData\\Local\\Temp',
                  'POGL_WINDOW_TYPE' => 'glut',
                  'USE_POGL' => '1',
                  'WITH_SLATEC' => '1',
                  'GSL_LIBS' => undef,
                  'PDL_CONFIG_VERSION' => '0.005',
                  'BADVAL_PER_PDL' => '0',
                  'WITH_DEVEL_REPL' => '1',
                  'SKIP_KNOWN_PROBLEMS' => '0',
                  'WITH_GD' => '1',
                  'HDF_INC' => undef,
                  'WITH_BADVAL' => '1',
                  'WITH_GSL' => '1',
                  'HTML_DOCS' => '1',
                  'GD_LIBS' => undef,
                  'HDF_LIBS' => undef,
                  'POSIX_THREADS_INC' => undef,
                  'MALLOCDBG' => {
                                   'libs' => '',
                                   'include' => ''
                                 },
                  'WITH_POSIX_THREADS' => '1',
                  'GD_INC' => undef,
                  'PDL_BUILD_DIR' => 'C:\\STRAWB~1\\data\\.cpanm\\work\\1496217394.1164\\PDL-2.018',
                  'WITH_MINUIT' => '1',
                  'WITH_IO_BROWSER' => '0',
                  'OPTIMIZE' => undef,
                  'PDL_BUILD_VERSION' => '2.018',
                  'POGL_VERSION' => '0.6702',
                  'PDLDOC_IGNORE_AUTOLOADER' => '0',
                  'FITS_LEGACY' => '1',
                  'BADVAL_USENAN' => '0',
                  'PROJ_LIBS' => undef,
                  'GD_DEFINE' => '',
                  'WITH_PROJ' => '1',
                  'WITH_3D' => '1'
                };
Summary of my perl5 (revision 5 version 26 subversion 0) configuration:

  Platform:
    osname=MSWin32
    osvers=6.3
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.26.0.1 #1 Wed May 31 04:42:31 2017 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='7.1.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++.exe'
    ldflags ='-s -L"C:\berrybrew\5.26.0_64_PDL\perl\lib\CORE" -L"C:\berrybrew\5.26.0_64_PDL\c\lib"'
    libpth=C:\berrybrew\5.26.0_64_PDL\c\lib C:\berrybrew\5.26.0_64_PDL\c\x86_64-w64-mingw32\lib C:\berrybrew\5.26.0_64_PDL\c\lib\gcc\x86_64-w64-mingw32\7.1.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl526.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\berrybrew\5.26.0_64_PDL\perl\lib\CORE" -L"C:\berrybrew\5.26.0_64_PDL\c\lib"'


```
 
```
perlDL shell v1.357
 PDL comes with ABSOLUTELY NO WARRANTY. For details, see the file
 'COPYING' in the PDL distribution. This is free software and you
 are welcome to redistribute it under certain conditions, see
 the same file for details.

Summary of my PDL configuration

VERSION: PDL v2.019 (supports bad values)

$%PDL::Config = {
                  'BADVAL_USENAN' => '0',
                  'FITS_LEGACY' => '1',
                  'POGL_WINDOW_TYPE' => 'glut',
                  'SKIP_KNOWN_PROBLEMS' => '0',
                  'POGL_VERSION' => '0.6702',
                  'MALLOCDBG' => {
                                   'libs' => '',
                                   'include' => ''
                                 },
                  'GD_LIBS' => undef,
                  'USE_POGL' => '1',
                  'HDF_LIBS' => undef,
                  'HIDE_TRYLINK' => '1',
                  'WITH_3D' => '1',
                  'GSL_INC' => undef,
                  'PROJ_LIBS' => undef,
                  'GD_INC' => undef,
                  'WITH_PROJ' => '1',
                  'PDL_BUILD_DIR' => 'C:\\STRAWB~2\\data\\.cpanm\\work\\1574394903.3752\\PDL-2.019',
                  'OPTIMIZE' => undef,
                  'TEMPDIR' => 'C:\\Users\\vadim\\AppData\\Local\\Temp',
                  'GL_BUILD' => '1',
                  'PDL_CONFIG_VERSION' => '0.005',
                  'WITH_SLATEC' => '1',
                  'POSIX_THREADS_LIBS' => undef,
                  'WITH_DEVEL_REPL' => '1',
                  'HTML_DOCS' => '1',
                  'PDL_BUILD_VERSION' => '2.019',
                  'WITH_GD' => '1',
                  'POSIX_THREADS_INC' => undef,
                  'PDLDOC_IGNORE_AUTOLOADER' => '0',
                  'BADVAL_PER_PDL' => '0',
                  'PROJ_INC' => undef,
                  'WITH_HDF' => '1',
                  'GSL_LIBS' => undef,
                  'WITH_IO_BROWSER' => '0',
                  'WITH_POSIX_THREADS' => '1',
                  'HDF_INC' => undef,
                  'WITH_GSL' => '0',
                  'GD_DEFINE' => '',
                  'WITH_MINUIT' => '1',
                  'MINUIT_LIB' => undef,
                  'WITH_BADVAL' => '1'
                };
Summary of my perl5 (revision 5 version 30 subversion 1) configuration:

  Platform:
    osname=MSWin32
    osvers=10.0.18363.476
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.30.1.1 #1 Fri Nov 22 02:24:29 2019 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++.exe'
    ldflags ='-s -L"C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\perl\lib\CORE" -L"C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\c\lib"'
    libpth=C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\c\lib C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\c\x86_64-w64-mingw32\lib C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl530.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\perl\lib\CORE" -L"C:\berrybrew\strawberry-perl-5.30.1.1-64bit-PDL\c\lib"'

```

**Comment by mohawk2** [comment] 2021-09-08 17:20
Using this on Ubuntu:

```
use Time::HiRes qw(gettimeofday tv_interval);
@t=gettimeofday(); $x=zeroes(100e6); p tv_interval(\@t);
```

it takes about 450ms. It takes extremely similar time to do with "byte", so it doesn't seem like the physical amount of RAM (100Mb vs 800Mb) is important here. It seems to scale linearly with number of elements, since with 150e6 elements of `byte` as below, it takes about 730ms. Using `ones` instead takes exactly the same amount of time.

`x=zeroes(150e6)` triggers the "BIGPDL" protection, as double (the default type) is 8 bytes. `$x=zeroes(byte, 150e6)` doesn't, so it's probably not allocating double then truncating (confirmed by code inspection, and some experiments which are ongoing).

**Comment by mohawk2** [comment] 2021-09-08 18:42
With the change just committed on `master`, the allocation stage on all of `ones`, `zeroes`, etc (in fact, during `pdl_allocdata` as called by `make_physical`) is very slightly slower as it always does a `memset` to 0. `zeroes` on double takes similar to before, but `zeroes` with byte is now about 8 times quicker, suggesting it now scales with quantity of bytes, not number of elements.

For comparison, this C code:

```c
#include <stdlib.h>
int size = 100000000;
int main() {
  int i;
  char *s = malloc(size);
  for (i=0; i<size; i++) s[i] = 1;
}
```

Takes about 320ms on my system to run when the "size" is 100e6, and about 500ms when it's 150e6. So it looks like PDL is going about as fast as we're likely to achieve, and e.g. `assgn` is probably not going to be possible to make a lot faster.

@vadim-160102 @d-lamb Do you feel there are remaining issues?

**Comment by mohawk2** [comment] 2021-09-28 15:16
Believing this is resolved, I will close this. However, please reopen if I am wrong!

**Closed by mohawk2** 2021-09-28 15:16 UTC
